language: php

php:
  - 7.1

env:
  - STABILITY="--prefer-lowest --prefer-stable"
  - STABILITY="" STYLE_CHECK=true

before_install:
  - if [[ $STYLE_CHECK ]]; then phpenv config-rm xdebug.ini; fi;
  - composer self-update

before_script:
  - if [[ ! $STYLE_CHECK ]]; then mkdir -p build/logs; fi;
  - composer update $STABILITY
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then COMMIT_RANGE=$TRAVIS_COMMIT_RANGE; else COMMIT_RANGE="HEAD~..HEAD"; fi;
  - if [[ $STYLE_CHECK ]]; then CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB $COMMIT_RANGE); fi;
script:
  - |
    if [[ $STYLE_CHECK ]]; then
      composer style-check src $CHANGED_FILES;
      composer style-check tests $CHANGED_FILES;
      phpunit --no-coverage;
    else
      phpunit;
    fi;

after_success:
   - if [[ ! $STYLE_CHECK ]]; then php vendor/bin/php-coveralls; fi;
