language: php

php:
  - 7.1

env:
  matrix:
    - STABILITY="--prefer-lowest --prefer-stable"
    - STABILITY=""

before_install:
  - composer self-update

before_script:
  - composer update $STABILITY

script:
  - mkdir -p build/logs
  - composer run-tests
  - composer style-check src
  - composer style-check tests

after_success:
   - php vendor/bin/php-coveralls
